### ISSUE TITLE
Implement update-attributes --who-pays-for-reads

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#319]
Implement update-attributes --who-pays-for-reads

The owner of a file should be able to change the read terms at any time on a particular file. It shouldn’t be on the receiver side, as they will always want it for free.

**Comment by moldis** [comment]
cc @kushthedude

**Comment by lpoli** [comment]
Actually owner can change the read terms and even if client sets who-pays to allocation owner it will be set to requesting client-id in download function.
And if allocation-owner wants himself to pay for the read and client requests with who-pays as himself then owner won't be charged in this case. Its the client who pays.

Above is the implementation but logic looks a bit flaky to me.

**Comment by Sriep** [comment]
I am not sure if this has been fixed. The problem is that the code in [object_operation_handler.go](https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/handler/object_operation_handler.go#L178) is a little confusing. It contains partially implemented code that it is unclear if it does anything. 

Are there system tests that check who-pays-for-reads? If not we should add some. I think this might overlap with https://github.com/0chain/blobber/issues/236.

**Comment by moldis** [comment]
I gonna pick up this ticket to check/refactor logic

**Comment by moldis** [comment]
The code includes rx_pay logic already, so I am just adding system_tests https://github.com/0chain/system_test/pull/231

**Comment by lpoli** [comment]
@guruhubb  Allocation owner can change this file attribute i.e. can set `WhoPays` variable to either owner or third party. But this information should be stored by blobber and blobber should apply it genuinely for the download request. i.e. We are depending on blobber on this.

I think we should put this `WhoPays` attribute in `auth ticket` itself so that it can be easily redeemed in blockchain as well.

Owner would create an authticket by also setting `WhoPays` and signs it. Blobber can take this information from authticket and serve the download request. And later on Storage smart contract can transfer tokens based on ReadMarker and Authticket.

cc @Sriep

**Comment by guruhubb** [comment]
I agree
