### ISSUE TITLE
Shared Files can not be retrieved when recovering a wallet from mnemonic/cloud

### ISSUE THREAD

**Issue by Sarthakbunny** [0chain/blobber#443]
On recovering wallet 0box/files will show the list of files from previous wallet but the 0box/share-file wont show the previous wallet files.

Reference: https://0chain.slack.com/archives/C026YA5EYH3/p1636702183147100

**Comment by shaktals** [comment]
So, re-reading the issue, from what I understand, the issue is that today we have to save the `auth_tickets` in the browser's localStorage so that the app knows what files have been shared with the current wallet. It that right @Sarthakbunny?

I just made some tests and that seems to be the case. I opened up a [discussion](https://0chain.slack.com/archives/C01U94VF56Y/p1638975464334200) on the #status channel on slack.

**Comment by shaktals** [comment]
As per Saswata comments on the above mentioned slack discussion, the feature is already implemented on explorer via `recover from mobile phone`. We'll just add an extra alert to the user if he doesn't have that feature set up for their wallet.
