### ISSUE TITLE
Disk load balancer for storing files (i.e. infinite storage)

### ISSUE THREAD

**Issue by moldis** [0chain/blobber#462]
Something similar to https://data-flair.training/blogs/hadoop-hdfs-disk-balancer/. During file upload, the blobber code should choose the disk to store file, download operation should pickup file from specific storage. Extra database column pointing to storage name.

Need to discuss about:
1. Choose algorithm pros and cons for load balancing (might be round robin, free space or mixed)
2. Dynamically connect storages or save in DB table to choose
3. Checking if storage available for write/read
4. What todo if one of storages broken/dissapeared, i.e. fallback strategy

**Comment by guruhubb** [comment]
I think we had several proposals for the algorithm, and the one I liked is to map file to disk irrespective of allocation. The mapping could be based on free storage space, file size, and inode value. The disk can be viewed as a storage entity and can be a RAID.  So then you'd be writing the file based on multiple RAIDs not disks.  We will likely recommend a 2-RAID5s to start with for a blobber. If a disk fails, it can be swapped out and the h/w or s/w RAID will recover lost data.

We need to make sure the database is high fault tolerant and stores its dB in master-slave configuration over multiple disks or RAIDs so that it can recover upon disk/RAID failure.

**Comment by lpoli** [comment]
We can have multiple raids setup for a system. So there can be n number of Raid-i's. 
Regarding load balancing we can have round-robin, min-size first, min-count first, random, some disk selection algorithm based on file size,etc.
We can also consider small sized files for example say, less than 1KB, to store in some database so inodes consumption will be taken care of.

For postgres db scaling there is `partition` and `tablespace` feature.

There is one issue, maybe irrelevant most of the time, but needs to be resolved with above approach.
So based on multiple disk, say n disks, blobber claims to have some capacity. It then contracts for multiple allocations. When disk starts to get used there can be situation that n disks have m unit of available space. So in total blobber has m*n available space.
Blobber then should be able to store files that is greater than `m and <= m*n`.

So because of this we might need to consider block level storage. i.e. For any blob that client sends we can divide it into blocks and spread it out into the disks if we have multi-raid system. We can enforce reserved space. For single raided system we can simply store blob as a whole.
Note; For each disk/partition, inodes number can be configured. In most system it is 1:16KB ratio.

Also directory structure is important here. We cannot put all files in same directory because it takes time for file lookups.
In sharder I've used `thousan` as maximum number of directories/files in a single directory.

**Comment by guruhubb** [comment]
@lpoli the above is a bit complex. Can we simplify as we have a few days to deliver this?  the less features and options we have in the algorithm the better.

We will not do block storage...too complex.

**Comment by lpoli** [comment]
This issue was raised keeping in mind that we are going to use multiple disks with multiple partitions.
Currently we are moving to Raid setup where unlimited storage capacity can be mounted in single partition. Therefore only file management inside single partition is a necessity.
