### ISSUE TITLE
Error: 'fcrd should not be nil' on endpoint /_statsJSON

### ISSUE THREAD

**Issue by peterlimg** [0chain/blobber#473]
@Manali-Jain-squareops reported error:

```sh
2021-12-21T22:31:40.192Z ERROR stats/blobberstats.go:218 fcrd should not be nil
github.com/0chain/blobber/code/go/0chain.net/blobbercore/stats.(*BlobberStats).loadFailedChallengeList
/0chain/code/go/0chain.net/blobbercore/stats/blobberstats.go:218
github.com/0chain/blobber/code/go/0chain.net/blobbercore/stats.LoadBlobberStats
/0chain/code/go/0chain.net/blobbercore/stats/blobberstats.go:111
github.com/0chain/blobber/code/go/0chain.net/blobbercore/stats.StatsJSONHandler
/0chain/code/go/0chain.net/blobbercore/stats/handler.go:490
```

This happens because `setStatsRequestDataInContext()` is not called on `StatsJSONHandler()`, therefore, no stats info saved to the context. There are some other stats acquiring issue happen in similar way, we'd better check the logs and fix them too.

**Comment by iamrz1** [comment]
Got it, this is because the pagination data for failed challenges is missing, which should have been added for jsonStats as well. So since the allocation list and failed challenge list is paginated, I will also return the pagination info with response.

And if there are any other stats related issues, please let me know.

**Comment by iamrz1** [comment]
In hindsight, statsJSON endpoint doesn't seem to serve allocation-list and failed-challenge-list. In that case, not serving the stats in json endpoint might be a good idea (since there's database calls involved).
