### ISSUE TITLE
directory copying should be supported on `zbox copy`

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#588]
please keep eyes on 
- WriteMarker
- FileStats

**Comment by stewartie4** [comment]
zbox: download, rename, move, delete & share folder also does not work

**Comment by Sriep** [comment]
~The problem with auth-tickets is due to [downloadFile](https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/handler/object_operation_handler.go#L259)~
```go
	// check out read pool tokens if read_price > 0
	err = readPreRedeem(ctx, alloc, dr.NumBlocks, pendNumBlocks, clientID)
	if err != nil {
		return nil, common.NewErrorf("download_file", "pre-redeeming read marker: %v", err)
	}
```
~This should check the read pool of the user paying for the read, which might not be the `clientID` as here. We should put back the `payerId` logic that was removed in https://github.com/0chain/blobber/pull/717~

Ok, the share functionality seems to have changed. So the code above looks fine.

**Comment by lpoli** [comment]
Reader is always the payer of the read.
