### ISSUE TITLE
request limit on CRUD operations 

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#671]
add a limit on the number of CRUD operations that the user can perform on an allocation to prevent Byzantine attacks.

**Comment by sculptex** [comment]
@cnlangzi If users are paying for CRUD operations then what is the issue? I am not sure about Move/Rename operations though, should they have fee?

Rate limiting will seriously damage UX, consider that only a small number of users might be performing CRUD operations at any point in time.

**Comment by sculptex** [comment]
@cnlangzi on re-reading the above, I should clarify that I agree we should prevent Byzantine attacks, but just make sure limits are not so strict as to infringe upon legitimate CRUD operations.

**Comment by avanaur** [comment]
@cnlangzi there seems to be an API rate limiter already in place based on caller IP (user). Although it was set to 0 at the moment.

https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/handler/handler.go#L37
https://github.com/0chain/blobber/blob/da3feebad661a56daffbaa17fc79554ed6d2d325/config/0chain_blobber.yaml#L71

do you still need separate rate limiting based on allocation regardless of caller IP (user)? I feel like this is more unlikely and if ever an allocation is targeted, it has to be distributed attack otherwise the rate limiting by IP will kick in (unless of course that was disabled).

**Comment by peterlimg** [comment]
Users are paying their CURD operations and we actually has the rate limit code implemented, so I'll close this issue.

**Comment by cnlangzi** [comment]
@peterlimg it doesn't work properly now. Because it has to be closed in ChunkUpload requests if a file is uploaded with a lot of chunks.  but we still need to limit other operations to prevent DDoS .  @Kishan-Dhakan  could you add a test on your DDoS testing? 
@avanaur  please try to improve it for ChunkUpload. Because chunk can be uploaded without paying. WriteMarker is processed only on CommitWrite stage.

**Comment by lpoli** [comment]
@avanaur What is the progress with this issue?
