### ISSUE TITLE
We need to get the list of recently added files

### ISSUE THREAD

**Issue by moldis** [0chain/blobber#702]
I believe it's possible to do with write markers, also we need pagination for this endpoint

**Comment by lpoli** [comment]
@moldis We cannot do it with write markers. We can only take timestamp from write marker and ask blobbers for recently updated files. For this all blobber's timestamp for file should be in sync in each other. We can achieve this if timestamp is taken from write markers for all refs while the commit request is made. So there are two tasks for this task.

1. Take timestamp from write marker so that all blobbers are in sync regarding time stamp for refs.
2. Use GetRefs endpoint to retrieve list of files.

**Comment by moldis** [comment]
@lpoli sounds good. Is it possible to merge it into single endpoint?
