### ISSUE TITLE
New owner cannot download encrypted file after allocation ownership is transferred 

### ISSUE THREAD

**Issue by stewartie4** [0chain/blobber#711]
After an allocation has been transferred, the new owner cannot download any file in the allocation that is encrypted, they can only download non-encrypted files from the allocation.

Steps to reproduce:

#SET UP ORIGINAL WALLET, ALLOCATION AND UPLOAD ENCRYPTED FILE
./zbox register
./zwallet faucet --methodName pour --tokens 1.000000 --input {}
./zbox newallocation --expire 1h --size 204800 --lock 0.5
./zbox upload --encrypt  --allocation <original_allocation_id> --remotepath /encrypted_file.txt --localpath ./file.txt

#CREATE A NEW WALLET, TRANSFER OWNERSHIP, CREATE READ POOL, ATTEMPT TO DOWNLOAD ENCRYPTED FILE
./zbox register
./zbox addcurator --allocation <original_allocation_id> --curator <second wallet>
./zwallet faucet --methodName pour --tokens 1.000000 --input {}
./zbox transferallocation --new_owner_key <second wallet public key> --new_owner <second wallet> --allocation <original_allocation_id>
./zbox list-all --allocation <original_allocation_id> (using new wallet) - should eventually pass once allocation ownership has changed
./zbox rp-lock --allocation <original_allocation_id> --tokens 0.5 --duration 1h
./zbox download --allocation <original_allocation_id> --localpath ./Downloads/file --remotepath /encrypted_file.txt

File download fails with 
Error in file operation: File content didn't match with uploaded file

**Comment by cnlangzi** [comment]
@guruhubb @peterlimg  is it possible to transfer an encrypt file to other guy? how to handle encryption key?

**Comment by sculptex** [comment]
This is known issue, draft NFT doc had explanation requiring re-processing of such encrypted files by new owner.

@cnlangzi My (interim) suggestion was that a (non-expiring) PRE share(s) to new owner be created before transfer and that we have facility to read files via those existing authtickets even though owner changed. This doesn't require any new tech.

**Comment by guruhubb** [comment]
Yes don't worry about this @cnlangzi. I agree with @sculptex. The new owner needs to get permission to download the encrypted files from previous owner, and then re-upload them which is not part of the protocol.

**Comment by cnlangzi** [comment]
@guruhubb so he has to download and re-upload file. and this issue can be closed. cc @stewartie4 @sculptex

**Comment by stewartie4** [comment]
Sorry I'm not getting something - the issue here is that the new owner cannot download the file 
So they'll not be able to re-encrypt and re-upload 

It's not sustainable for important encrypted files to be perminantly inaccessible to the new owner without warning

**Comment by lpoli** [comment]
@stewartie4 the logic is that the owner who is supposed to transfer allocation is supposed to provide re-encryption key to the new owner so that later on he can download and upload it again. 

New owner needs to download the file and re-decrypt it and upload to the allocation. Little work still needs to be done. Current implementation has  re-decryption associated with auth-ticket. For the new owner authticket is not required.  So we need to have download function that takes re-encryption key to re-decrypt the encrypted file.
cc @cnlangzi @guruhubb

**Comment by stewartie4** [comment]
Yep that's what i'm getting at - today we don't have this ability 
The CLI could handle this for the end user by retrieving the key and re-uploading (ideal)
OR
We add a flag on download that allows us to provide the key manually (not ideal)

Either way I think a change needs made to support this properly because today these files are inaccessible forever

**Comment by cnlangzi** [comment]
@stewartie4  as @sculptex 's suggestion

1. owner share encrypt file by PRE to new owner. It is an auth-ticket
2. new owner download encrypt file by the auth-ticket first.
3. owner transfer his allocation to new owner
4. new owner upload encrypt file to his allocation

does it work via cli now?

**Comment by lpoli** [comment]
@cnlangzi So if there are thousands of such encrypted files then owner needs to generate authtickets for all the files and provided to new owner. New owner has to download all those thousands files one by one and store it in local. After owner transfers his allocation new owner has to upload them all.

It seems too much tedious work.

Better is;
1. owner generate re-encryption key and provide it to the new owner. Re-encryption key is always same. 
2. owner will transfer the allocation. step 1 & 2 can be in any order.
3. New owner does not require any authticket because it is his allocation now.
4. He will check encrypted files in the allocation, downloads it, re-decrypts it and encrypt with his private keys and update file to the allocation.

We could have a function in gosdk to do this.

**Comment by sculptex** [comment]
@lpoli  just to clarify in context of NFTs for which this feature was introduced, many encrypted files will probably not be typical. Encrypted NFTs are just an option, currently NFTs stored on IPFS don't even have this ability!

However, it sounds like your suggestion is similar to mine but without the need for authticket(s)? In which case it's obviously a good option.

But please just clarify, is all we are really talking about is the ability to specify the public_encryption_key as being one other than the current owner? (Previous owner).

If we have to transfer any private keys to new owner then it creates a fresh problem.

**Comment by lpoli** [comment]
@sculptex Exactly yes. We don't need previous owner's private key or whatsoever. We only need re-encryption key from previous owner.

**Comment by guruhubb** [comment]
@lpoli @stewartie4 we're not doing this on the protocol or cli. The application can do this. lets not waste any more time on this
