### ISSUE TITLE
blobber config should allow differing configs for each blobber

### ISSUE THREAD

**Issue by sculptex** [0chain/blobber#77]
currently, clobbercore/config/config.go loads settings from config/0chain_blobber.yaml for all blobbers. There are various circumstances where different configs may wish to be used for different blobbers in same machine. There needs to be a consistent way to do this rather than just change config each time prior to starting blobber.

One idea is if blobber number N is known (or can be specified by additional parameter), it could check for 0chain_blobberN.yaml and using that if present, if not then default to 0chain_blobber.yaml. Alternatively, always load 0chain_blobber.yaml then load additional settings to override defauls from 0chain_blobberN.yaml if present so the individual blobber files only store specific differences

**Comment by guruhubb** [comment]
You can override defaults using ./zbox bl-update for individual blobber settings and can write a script for such. But in general, you want one blobber per server instead of multiple blobbers per server. However for a large server, you can use 0miner to spin up multiple blobbers and then use the rancher to change settings for each blobber. The only thing the blobber will need to change is capacity which is infrequent.  The price can be set in USD, and other settings such as min_lock_demand and stakes are expect to be very infrequent.

**Comment by sculptex** [comment]
Multiple blobbers per server (one blobber per physical HDD) is the only way to achieve optimum $/TB. A single blobber spanning multiple disks increases risk of failure unless raid is used which increases costs plus wear and tear. Also multiple blobbers allows varying size disks/types to be used (e.g. premium SSD + HDD). I will close this because zbox bl-update option is available but still think it should accomodate config based solution
