### ISSUE TITLE
Pull request test always gives false positive

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#98]
The [pull request test](https://github.com/0chain/blobber/blob/master/.github/workflows/ci.yml#L13) always passes, irrespective of unit test results. This needs to be fixed so that the pull requests test check passes or fails depending on unit tests results.

[Example of passing check with failed unit tests](https://github.com/0chain/blobber/runs/2419289779)

**Comment by shravanshetty1** [comment]
Other github actions are also not failing on bad exit codes, have not seemed to figure out issue so far

**Comment by shravanshetty1** [comment]
@Sriep Since we merged all the go.mod file, this issue has been resolved. This issue was being created since, previous code to run tests was this -

```
@for mod_file in $$(find * -name go.mod); do mod_dir=$$(dirname $$mod_file); (cd $$mod_dir; go test ./...); done
```

The problem with this code is that the exit code returned will be that of the last command run. This means that if a test fails for packages and passes for the last package. It will return exit code 0, since the last package test passed.
